//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleos
    {
        public Empleos()
        {
            this.HistorialEmpleos = new HashSet<HistorialEmpleos>();
        }
    
        public int Codigo { get; set; }
        public string Nombre_empleo { get; set; }
        public decimal Salario_minimo { get; set; }
        public decimal Salario_maximo { get; set; }
    
        public virtual ICollection<HistorialEmpleos> HistorialEmpleos { get; set; }
    }
}
